### ISSUE TITLE
About

### ISSUE THREAD

**Issue by ligang2425** [BroadbandForum/obudpst#12]

**Comment by ligang2425** [comment]
Hi,I have a problem, in the protocol.md file, the size of the setupreq PDU is supposed to be 48 bytes, but why is it actually showing 52 bytes when I am doing the test?
As shown in the picture:
![setupReq_PDU](https://github.com/BroadbandForum/obudpst/assets/53633664/ac75bf8d-7b97-4a4c-8a4b-204dd70b95cd)

**Comment by lc9892** [comment]
Hello,
Sorry, the information in that file was not being kept up to date with the latest software changes and was actually mostly a duplicate for an IP Capacity Protocol Draft in the works (https://datatracker.ietf.org/doc/draft-ietf-ippm-capacity-protocol/). As such, the file has been removed from the latest version of the software that is set to release in the next couple of weeks. Also, a much-updated version of the protocol draft will be available soon. Although it will be closer to the protocol specific fields in the current software, in most regards, it will also describe new/yet-to-be-implemented enhanced security features that include additional message authentication and encryption. Again, sorry if it caused any confusion.

**Comment by ligang2425** [comment]
problem is ok
